"""Claim Reviewer: pre-filing checks on a draft Claim.

Three responsibilities:

1. **Pyramiding (§4.14)** — same symptom rated under more than one Diagnostic
   Code. We detect when two Claimed Conditions share an Anatomy + Symptom and
   record a ``:User:Weakness`` node naming the conflict.

2. **Bilateral Factor (§4.26)** — when a veteran has claimed only one side of a
   paired Anatomy (left knee but not right knee, etc.), prompt about the other
   side. Detected via the ``:PAIRED_WITH`` edges between Anatomy nodes (slice
   #5 populated these from ``data/anatomy.yaml``). Returned as prompts, not
   weaknesses — the agent asks; the veteran answers.

3. **Missing Evidence enumeration** — per Claimed Condition, list which
   Evidence types are still needed (STR / Lay Statement / Buddy Statement /
   Private Medical Record). The Lay Statement is generated by slice #9's
   drafter; we treat it as "to be drafted" rather than missing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from uuid import uuid4

from ..graph.driver import GraphDriver

# Evidence types we surface as "to gather". "Lay Statement" is omitted because
# the agent drafts it in slice #9 — it's "to be drafted", not "missing".
GATHERABLE_EVIDENCE_TYPES = (
    "Service Treatment Record",
    "Buddy Statement",
    "Private Medical Record",
)


@dataclass
class PyramidingConflict:
    dc_codes: list[str]
    anatomy: str
    symptom: str | None
    explanation: str


@dataclass
class BilateralPrompt:
    anatomy: str
    paired_anatomy: str
    dc_codes_on_claimed_side: list[str]


@dataclass
class ReviewReport:
    user_id: str
    claim_id: str
    pyramiding: list[PyramidingConflict] = field(default_factory=list)
    bilateral_prompts: list[BilateralPrompt] = field(default_factory=list)
    missing_evidence: dict[str, list[str]] = field(default_factory=dict)


def create_claim(driver: GraphDriver, user_id: str, dc_codes: list[str]) -> str:
    """Create a ``:User:Claim`` node and link it to ``:User:ClaimedCondition``
    nodes for each ``dc_code``. Returns the claim id."""
    claim_id = str(uuid4())
    driver.user_write(
        user_id,
        """
        MERGE (v:User:Veteran {user_id: $user_id})
        MERGE (cl:User:Claim {id: $claim_id})
          SET cl.user_id = $user_id, cl.status = 'draft', cl.created_at = datetime()
        MERGE (v)-[:HAS_DRAFT_CLAIM]->(cl)
        """,
        params={"claim_id": claim_id},
    )
    for code in dc_codes:
        driver.user_write(
            user_id,
            """
            MATCH (cl:User:Claim {id: $claim_id, user_id: $user_id})
            MATCH (dc:CFR:DiagnosticCode {code: $code})
            MERGE (cc:User:ClaimedCondition {id: $cc_id})
              SET cc.user_id = $user_id, cc.dc_code = $code
            MERGE (cl)-[:CLAIMS]->(cc)
            MERGE (cc)-[:MAPS_TO]->(dc)
            """,
            params={"claim_id": claim_id, "code": code, "cc_id": str(uuid4())},
        )
    return claim_id


def review_claim(driver: GraphDriver, user_id: str, claim_id: str) -> ReviewReport:
    """Run all pre-filing checks on a Claim and return a ReviewReport.

    Side effects: writes :User:Weakness nodes for Pyramiding conflicts.
    Bilateral prompts are NOT persisted — they're suggestions the agent acts on.
    """
    report = ReviewReport(user_id=user_id, claim_id=claim_id)
    report.pyramiding = _detect_pyramiding(driver, user_id, claim_id)
    report.bilateral_prompts = _detect_bilateral_prompts(driver, user_id, claim_id)
    report.missing_evidence = _enumerate_missing_evidence(driver, user_id, claim_id)
    _persist_weaknesses(driver, user_id, claim_id, report.pyramiding)
    return report


def _detect_pyramiding(
    driver: GraphDriver, user_id: str, claim_id: str
) -> list[PyramidingConflict]:
    """Two Claimed Conditions pyramid if they rate the same Anatomy + Symptom
    combination. For v1 we approximate: any two DCs in the same Claim that
    share an Anatomy (via ``:RATES`` or ``:HAS_MEASUREMENT->:OF_ANATOMY``) are
    flagged for review.
    """
    rows = driver.user_read(
        user_id,
        """
        MATCH (cl:User:Claim {id: $claim_id, user_id: $user_id})-[:CLAIMS]->(cc:User:ClaimedCondition)
              -[:MAPS_TO]->(dc:CFR:DiagnosticCode)
        OPTIONAL MATCH (dc)-[:HAS_RATING]->()-[:REQUIRES]->(c:Criterion)-[:HAS_MEASUREMENT]->(m:Measurement)
        OPTIONAL MATCH (dc)-[:RATES]->(rated_anatomy:Anatomy)
        WITH dc.code AS dc_code,
             collect(DISTINCT coalesce(m.body_part, rated_anatomy.name)) AS anatomies
        RETURN dc_code, [a IN anatomies WHERE a IS NOT NULL] AS anatomies
        """,
        params={"claim_id": claim_id},
    )

    by_anatomy: dict[str, list[str]] = {}
    for row in rows:
        for a in row["anatomies"] or []:
            by_anatomy.setdefault(a.lower(), []).append(row["dc_code"])

    conflicts: list[PyramidingConflict] = []
    for anatomy, codes in by_anatomy.items():
        unique = sorted(set(codes))
        if len(unique) >= 2:
            conflicts.append(
                PyramidingConflict(
                    dc_codes=unique,
                    anatomy=anatomy,
                    symptom=None,
                    explanation=(
                        f"DC {', DC '.join(unique)} all rate the same anatomy ({anatomy}). "
                        f"Under §4.14, the same symptom cannot be rated under multiple "
                        f"Diagnostic Codes — pick the one that best fits the veteran's "
                        f"presentation."
                    ),
                )
            )
    return conflicts


def _detect_bilateral_prompts(
    driver: GraphDriver, user_id: str, claim_id: str
) -> list[BilateralPrompt]:
    """For each claimed Anatomy that has a contralateral pair, check whether
    the veteran has a SymptomReport on the OTHER side. If not, emit a prompt.
    """
    rows = driver.user_read(
        user_id,
        """
        MATCH (cl:User:Claim {id: $claim_id, user_id: $user_id})-[:CLAIMS]->(cc:User:ClaimedCondition)
              -[:MAPS_TO]->(dc:CFR:DiagnosticCode)
        OPTIONAL MATCH (dc)-[:RATES]->(rated:CFR:Anatomy)
        OPTIONAL MATCH (dc)-[:HAS_RATING]->()-[:REQUIRES]->(:Criterion)
                       -[:HAS_MEASUREMENT]->(:Measurement)-[:OF_ANATOMY]->(meas_anatomy:CFR:Anatomy)
        WITH dc.code AS dc_code,
             collect(DISTINCT rated.name) + collect(DISTINCT meas_anatomy.name) AS anatomy_names
        UNWIND anatomy_names AS anatomy_name
        WITH dc_code, anatomy_name
        WHERE anatomy_name IS NOT NULL
        MATCH (a:CFR:Anatomy {name: anatomy_name})-[:PAIRED_WITH]->(paired:CFR:Anatomy)
        RETURN DISTINCT dc_code, anatomy_name AS anatomy, paired.name AS paired_anatomy
        """,
        params={"claim_id": claim_id},
    )

    # Group by (anatomy, paired_anatomy) and collect dc_codes.
    by_pair: dict[tuple[str, str], list[str]] = {}
    for row in rows:
        key = (row["anatomy"], row["paired_anatomy"])
        by_pair.setdefault(key, []).append(row["dc_code"])

    # For each pair, check whether the veteran also has a SymptomReport on the
    # paired anatomy. If yes, no prompt. If no, emit a prompt.
    prompts: list[BilateralPrompt] = []
    for (anatomy, paired_anatomy), dc_codes in by_pair.items():
        has_paired_report = driver.user_read(
            user_id,
            """
            MATCH (v:User:Veteran {user_id: $user_id})-[:REPORTED]->(sr:User:SymptomReport)
                  -[:LOCATED_IN]->(a:CFR:Anatomy)
            WHERE a.name = $paired
            RETURN count(sr) AS c
            """,
            params={"paired": paired_anatomy},
        )
        if has_paired_report and has_paired_report[0]["c"] > 0:
            continue
        prompts.append(
            BilateralPrompt(
                anatomy=anatomy,
                paired_anatomy=paired_anatomy,
                dc_codes_on_claimed_side=sorted(set(dc_codes)),
            )
        )
    return prompts


def _enumerate_missing_evidence(
    driver: GraphDriver, user_id: str, claim_id: str
) -> dict[str, list[str]]:
    """Per Claimed Condition, list which Evidence types are not yet attached.

    Lay Statement is excluded (it gets drafted in slice #9). Service Treatment
    Record, Buddy Statement, and Private Medical Record are the "to gather"
    items.
    """
    rows = driver.user_read(
        user_id,
        """
        MATCH (cl:User:Claim {id: $claim_id, user_id: $user_id})-[:CLAIMS]->(cc:User:ClaimedCondition)
              -[:MAPS_TO]->(dc:CFR:DiagnosticCode)
        OPTIONAL MATCH (cc)-[:SUPPORTED_BY]->(e:User:Evidence)
        WITH dc.code AS code, collect(DISTINCT e.type) AS attached
        RETURN code, [t IN attached WHERE t IS NOT NULL] AS attached
        """,
        params={"claim_id": claim_id},
    )
    out: dict[str, list[str]] = {}
    for row in rows:
        present = set(row["attached"] or [])
        missing = [t for t in GATHERABLE_EVIDENCE_TYPES if t not in present]
        out[row["code"]] = missing
    return out


def _persist_weaknesses(
    driver: GraphDriver,
    user_id: str,
    claim_id: str,
    conflicts: list[PyramidingConflict],
) -> None:
    for conflict in conflicts:
        driver.user_write(
            user_id,
            """
            MATCH (cl:User:Claim {id: $claim_id, user_id: $user_id})
            MERGE (w:User:Weakness {
                user_id: $user_id, claim_id: $claim_id, kind: 'pyramiding', anatomy: $anatomy
            })
              SET w.dc_codes = $dc_codes,
                  w.explanation = $explanation,
                  w.citation = '38 CFR §4.14',
                  w.recorded_at = datetime()
            MERGE (cl)-[:HAS_WEAKNESS]->(w)
            """,
            params={
                "claim_id": claim_id,
                "anatomy": conflict.anatomy,
                "dc_codes": conflict.dc_codes,
                "explanation": conflict.explanation,
            },
        )
